name: Nightly test execution

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  smoke-tests:
    name: Smoke tests
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Running smoke tests"