name: Nightly test execution

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Env name'
        required: true

jobs:
  smoke-tests:
    name: Smoke tests
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: |
          npm install
          npm test


      - name: Set environment variable
        run: echo "YOUR_VARIABLE_NAME=${{ github.event.inputs.env_name }}" >> $GITHUB_ENV
