name: Nightly test execution

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'dev'
        options:
          - dev
          - staging
          - production

jobs:
  smoke-tests:
    name: Smoke tests
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: |
          npm install
          npm test


      - name: Set environment variable
        run: echo "ENVIRONMENT=${{ github.event.inputs.environment || 'dev' }}" >> $GITHUB_ENV
