name: Nightly test execution

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  smoke-tests:
    name: E2E tests
    needs: [deploy]
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Run tests
        run: |
          npm install
          npm test